Seen phrases
onja-org/malagasy-rn-Mercury pull request #11
Opened 2021-06-04 06:04 UTC by bakozetra

Hello everyone, 
I have finished the seen-phrases. Have a look at it when you have free time.

2021-06-04 08:13 UTC, voromahery requested changes

2021-06-04 08:13 UTC, voromahery commented on package.json
> +    "react-thunk": "^1.0.0",
Its better to delete one of the redux-thunk in the json by uninstall it then reinstall it again

2021-06-08 09:45 UTC, andrzej-onja approved these changes

2021-06-08 11:03 UTC, voromahery approved these changes

2021-06-08 11:03 UTC, vahona approved these changes

2021-06-08 11:24 UTC, merged