Button switch languages
onja-org/malagasy-rn-Mercury pull request #3
Opened 2021-05-21 08:18 UTC by vahona

Hello there,

Finished the switch language feature, please have a look at it whenever you have time.

2021-05-25 06:17 UTC, andrzej-onja requested changes
So far looks good but we need another change:

please create file src/translations/index.js

2021-05-25 06:17 UTC, andrzej-onja commented on package.json
> +    "react-native-i18n": "^2.0.15",
this package seems to be unused, remove please

2021-05-25 06:17 UTC, andrzej-onja commented on package.json
> +    "react-native-i18n": "^2.0.15",
this package seems to be unused, remove please

2021-05-25 06:17 UTC, andrzej-onja commented on src/screens/Learning.js
> +            <SectionHeading text={nativeLanguage === LANGUAGE_NAMES.EN ? "Category: " : "Sokajy :"} />
create a file src/translations/index.js

```
export const CATEGORY_HEADING = 'CATEGORY_HEADING';


export const LANG_DATA = {
    [CATEGORY_HEADING]: {
    [LANGUAGE_NAMES.EN]: 'Category:',
    [LANGUAGE_NAMES.MG]: 'Sokajy: ',
  },
  
};
```

then you can get the translation like this

`const categoryHeading = LANG_DATA[CATEGORY_HEADING][nativeLanguage];`

then 
 ` <SectionHeading text={categoryHeading} />`

2021-05-26 06:17 UTC, andrzej-onja commented on src/screens/Home.js
> +} from '../redux/constants'
those constants should be in translation file as its not related to redux

2021-06-04 08:13 UTC, andrzej-onja approved these changes

2021-06-04 08:38 UTC, voromahery approved these changes

2021-06-04 08:38 UTC, Mickaellah approved these changes

2021-06-04 08:41 UTC, merged